//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.24 at 11:59:10 PM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://TARS/InspectionWS.tws", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.example.webfluxdemo.schemas.inspection;
