//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.24 at 11:59:10 PM PDT 
//


package com.example.webfluxdemo.schemas.inspection;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="inspectionRequest" type="{http://TARS/InspectionWS.tws}InspectionRequest"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "inspectionRequest"
})
@XmlRootElement(name = "startProcess")
public class StartProcess {

    @XmlElement(required = true)
    protected InspectionRequest inspectionRequest;

    /**
     * Gets the value of the inspectionRequest property.
     * 
     * @return
     *     possible object is
     *     {@link InspectionRequest }
     *     
     */
    public InspectionRequest getInspectionRequest() {
        return inspectionRequest;
    }

    /**
     * Sets the value of the inspectionRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link InspectionRequest }
     *     
     */
    public void setInspectionRequest(InspectionRequest value) {
        this.inspectionRequest = value;
    }

}
