//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.04 at 12:26:29 AM PDT 
//


package com.example.webfluxdemo.schemas.inspection;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ViolationInfoBO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ViolationInfoBO"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="violationType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="violationCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="incidentZone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="incidentAddressCoordinates" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="violationDetails" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ViolationInfoBO", propOrder = {
    "violationType",
    "violationCode",
    "incidentZone",
    "incidentAddressCoordinates",
    "violationDetails"
})
public class ViolationInfoBO {

    protected String violationType;
    protected String violationCode;
    protected String incidentZone;
    protected String incidentAddressCoordinates;
    protected String violationDetails;

    /**
     * Gets the value of the violationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getViolationType() {
        return violationType;
    }

    /**
     * Sets the value of the violationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setViolationType(String value) {
        this.violationType = value;
    }

    /**
     * Gets the value of the violationCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getViolationCode() {
        return violationCode;
    }

    /**
     * Sets the value of the violationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setViolationCode(String value) {
        this.violationCode = value;
    }

    /**
     * Gets the value of the incidentZone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIncidentZone() {
        return incidentZone;
    }

    /**
     * Sets the value of the incidentZone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIncidentZone(String value) {
        this.incidentZone = value;
    }

    /**
     * Gets the value of the incidentAddressCoordinates property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIncidentAddressCoordinates() {
        return incidentAddressCoordinates;
    }

    /**
     * Sets the value of the incidentAddressCoordinates property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIncidentAddressCoordinates(String value) {
        this.incidentAddressCoordinates = value;
    }

    /**
     * Gets the value of the violationDetails property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getViolationDetails() {
        return violationDetails;
    }

    /**
     * Sets the value of the violationDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setViolationDetails(String value) {
        this.violationDetails = value;
    }

}
